language: go

go:
  - 1.12.x
go_import_path: mo-gateway

before_install:
  - go get -v github.com/json-iterator/go
  - go get -v google.golang.org/grpc

install: true

script:
  - make test
  - make build
  - make docker-read
  
before_deploy:
  - tar -zcf docker_build.tar.gz docker_build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - bin/*
    - docker_build.tar.gz
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - $NOTIFACTION_EMAIL
  webhooks:
    urls:
      - $MYWEBHOOKURL
